### ISSUE TITLE
Consider removing utility functions / properties from the spec

### ISSUE THREAD

**Issue by bialpio** [immersive-web/webxr#507] opened 2019-02-04 18:14 UTC
Currently, the spec contains few properties that could be considered "utility / helper" - they don't make the specification more capable, but only reduce the amount of code that app developer needs to write. Depending on our philosophy of what the spec should contain (ex. expose smallest API surface that is needed to enable content creators), we might want to remove such methods and pay attention to not add more of them.

Examples of helper / utility properties:
- `XRRigidTransform.matrix` - returns transformation matrix out of a translation vector and orientation quaternion.
- `XRRay.matrix` - returns transformation matrix out of translation and direction vectors.

Both of the above methods could be implemented in JavaScript and as such do not increase the capabilities of WebXR API.

In addition, the result of `XRRay.matrix` as described in the spec is non-unique - if we decide to keep it in the spec, we should describe the exact calculations that need to be performed, otherwise we are risking running into compatibility issues. Please let me know if you think this should be moved to a separate issue.

**Comment by cwilso** [comment] 2019-02-05 00:14
Given this might cause breakage, probably best to make a call sooner rather than later?

**Comment by Manishearth** [comment] 2019-04-02 18:12
I think a very common use case will be passing this down to openGL as a view matrix (after inversion), so it's pretty useful to have matrices directly exposed.

Most WebXR users probably will have a matrix math library so they _can_ construct these on their own, however the problem is that by not exposing the matrix we require users who want matrices to care about which order position/orientation apply in -- the matrix library will understand matrices, but not necessarily understand `XRRigidTransform`. This is particularly tricky with 3DOF devices where messing this up won't cause glaringly obvious issues during testing (since this only messes up neck modeling, which isn't something that is immediately noticeable when testing)

**Comment by toji** [comment] 2019-04-05 17:18
Thanks for the comment, @Manishearth. I think that illuminates our position pretty well. 

My recollection from the call this week was that we effectively said that we would keep these utility functions around but be willing to remove them if we receive guidance from the TAG or similar authoritative voice on the web platform that they should be removed. As a result, I'm closing this issue.

**Closed by toji** 2019-04-05 17:18 UTC
Labels: agenda, potential breaking change

**Comment by ddorwin** [comment] 2019-04-05 20:32
@bialpio Please file a separate issue for the last paragraph of your original report.

**Comment by bialpio** [comment] 2019-04-05 22:28
Opened issue #582.
