### ISSUE TITLE
Specify when we enter/exit immersive mode and what the baseLayer setter does

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#453] opened 2018-12-20 23:46 UTC
It's unclear to me exactly when we're supposed to enter or exit immersive mode.

`requestSession()` returns a session, but without a `baseLayer` can it be in immersive mode? We should specify this.

Similarly, what happens when you set `baseLayer` to null? Or change it? The baseLayer setter needs to be filled out

**Comment by kearwood** [comment] 2018-12-28 23:58
I agree we should define what happens when baseLayer is null.  Perhaps a reasonable expectation would be to render black (VR) or transparent (AR)?

**Comment by Manishearth** [comment] 2018-12-29 00:03
Worth noting: baseLayer will always be null on initialization, ideally `requestSession` has a way to provide a baseLayer?


(If I'm assuming correctly that requestSession is what starts immersive mode)

**Comment by NellWaliczek** [comment] 2019-01-04 00:31
@toji this is related to the changes we've been working on to batch render state into a single object.  When that PR is posted, let's link it to this issue and make sure it addresses the behavior of the rendering when baseLayer is null.

**Comment by Manishearth** [comment] 2019-01-08 02:17
Is there any reason for being able to mutate baseLayer at all (as opposed to setting it during initialization the way WebVR handles it)?

Being able to change baseLayer complicates the RAF code.

**Comment by asajeffrey** [comment] 2019-02-16 21:23
In the current spec (https://immersive-web.github.io/webxr/#xrrenderstate-interface), `baseLayer` is `readonly`, and is initialized to `null`. I don't see anything that subsequently sets it to a non-null value.

**Comment by Manishearth** [comment] 2019-02-17 02:14
Right, the user currently manually sets it.

**Comment by asajeffrey** [comment] 2019-02-17 02:30
Er, how? The attribute is `readonly`.

**Comment by Manishearth** [comment] 2019-02-17 02:33
Oh, sorry, stuff changed. `updateRenderState` queues up new baseLayers now.

**Comment by asajeffrey** [comment] 2019-02-17 02:44
Ah, that's where it's hidden!

I fell down this rabbit-hole from #528, trying to work out whether the `XRSession` is allowed to provide a `XRWebGLRenderingContext` (which it could do in whatever GL context it pleases) or have to use one provided by the user (which will be in the browser's GL context).

**Comment by toji** [comment] 2019-02-27 19:53
`baseLayer` is mutatable (via `updateRenderState`, as pointed out by @Manishearth) because we know that manipulating the layers being used will be an important part of the API in the future, especially when used multiple layers can be used at once.

A more immediate use, however, would simply be swapping out the base layer to change resolution, as the current `XRWebGLLayer` is defined to retain the same renderbuffer resolution for the lifetime of the object. So if you wanted to render, say, a 3D scene at a lower resolution for performance but then swap to a higher res buffer for a video sequence you would do that today by swapping between to `XRWebGLLayer`s.

In terms of how a session handles the lack of a `baseLayer`, it's a little obscure in the spec because it's part of the algorithm text but the intended behavior is that the session will work as usual but not process any `requestAnimationFrame` callbacks. Since having an active `XRFrame` is the only way to track the device pose, this effectively prevents tracking or rendering overhead when you don't have a `baseLayer`. Once one has been added the next regularly scheduled vsync should trigger any pending rAF callbacks.

**Closed by toji** 2019-02-27 19:53 UTC
