### ISSUE TITLE
Describe circumstances when a reference space type might be rejected.

### ISSUE THREAD

**Issue by AdaRoseCannon** [immersive-web/webxr#470] opened 2019-01-11 16:37 UTC
BS Issue: https://immersive-web.github.io/webxr/#issue-5b216b53

Context https://immersive-web.github.io/webxr/#xrreferencespace-interface

The algorithm in https://immersive-web.github.io/webxr/#xrreferencespace doesn't leave room for the referenceSpace creation to fail, although it's clear from the text above that it might (e.g. if the type is 'bounded' or 'unbounded' and such is not supported by the XR device and the XRSession).

The circumstances when it might not be supported should be described, and the algorithm amended to account for that.

**Comment by cwilso** [comment] 2019-04-29 22:53
Duplicate of #564

**Closed by cwilso** 2019-04-29 22:53 UTC
