### ISSUE TITLE
Beginning media playback once VR has started

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#316] opened 2018-01-10 18:23 UTC
A common request I've heard from developers (which was touched on again in #315) is that they want to begin playing media (usually a video, but audio comes up a lot too) once a user has fully entered VR. Since these require user activation to play, as does the creation of a session, and because the start of VR presentation after the session request is asynchronous, it means that in browser today the user activation token is basically guaranteed to have expired by the time `requestSession` resolves, so attempting to start media playback fails.

In my opinion the most straightforward way to address this is to have `requestSession` "carry forward" any user activation to it's promise resolution. IE: If requestSession is called in response to a user activation, it's promise resolution will also be a user activation. The main issue with that is that new `.then`s can be attached to a promise long after it's resolved, and we don't want those promises to be a user activation dispenser from that point forward, so we'd have to spec it as only carrying forward to the initial resolve, which is confusing and nothing else on the platform acts that way (that I'm aware of).

Another approach is that user activation is being changed to be defined as "the chain of such algorithms started within a user-agent defined timeframe.", with the spec giving a specific example of:

> if a user clicked a button, it might be acceptable for a popup to result from that after 4 seconds, but it would likely not be acceptable for a popup to result from that after 4 hours.

We could rely on this behavior and strive to ensure that our exclusive session requests resolve within the user agent defined timeframe, but I don't know if any browser support this change to the spec yet.

Thoughts on those approaches or ideas for other ways to address the issue? I feel like we've discussed this as a group before, but the explainer doesn't address it currently so no matter what our plan is I want to get it down in writing.

**Comment by cvan** [comment] 2018-01-12 05:45
I suggest we allow users to express these intents using the combination of either/or (in the following, prioritised order):

1. HTTP Response header, for example: `XR-Autoplay: true` or `XR-Autoplay: *` (à la `Accept-Language: fr-CH, fr; q=0.9, en; q=0.8, de; q=0.7`) — fastest (but unlikely to be supported out of the box by static web hosts, such as GitHub Pages, without filename sniffing or presence of files at known endpoints, à la `robots.txt`)
2. `<meta type="http-equiv" content="…>` — (à la `<meta name="viewport" content="…">`)
4. Values from the [Web-App Manifest](https://w3c.github.io/manifest/) (à la `<meta name="manifest" href="manifest.webmanifest">`)
3. _(optional)_ Programatically with a JS API (à la [`L20n.lang.code = 'fr'` using L20n/L10n](http://l20n.org)).

Thoughts?

**Comment by Manishearth** [comment] 2019-09-19 05:38
Dupe of #779

**Closed by Manishearth** 2019-09-19 05:38 UTC
Labels: editor triage
