### ISSUE TITLE
How can an author determine if the a feature was granted

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1148] opened 2020-12-05 18:37 UTC
If an author asks for `layers` in `requestSession`, they have no way to determine if it was granted apart from brute-forcing it by requesting a cubelayers.
Should we add a way to returns what features were granted?

**Comment by Maksims** [comment] 2020-12-05 19:43
This is somewhat an issue for writing code against ungranted APIs. It it requires to make some bespoke checks for each API to see if it was granted based on available functionality.
This probably even wont work where platform supports feature, but no permission was granted.

**Comment by Manishearth** [comment] 2020-12-06 07:17
Duplicate of https://github.com/immersive-web/webxr/issues/794

This already exists via the permission API integration, you run [`navigator.permissions.query()`](https://w3c.github.io/permissions/#dom-permissions-query) with an [`XRPermissionDescriptor`](https://immersive-web.github.io/webxr/#dictdef-xrpermissiondescriptor).

I don't think this has been implemented in any browser just yet, but there was general agreement as to this being the right way to do this (and i think Chromium has or planned to internally refactor to use the permissions API anyway).

cc @klausw who might know more about the implementation timeline for Chromium

**Closed by Manishearth** 2020-12-06 07:17 UTC

**Comment by cabanier** [comment] 2020-12-06 09:26
Until that feature lands (and it's been in limbo for several years), there is no way to check.
@klausw do you know if there is any movement on getting it landed? I know the implementation is pretty much complete in Chromium so this would just be on the spec front.

**Comment by Manishearth** [comment] 2020-12-06 17:00
@cabanier I don't think it's been in limbo for several years, it was specced a year ago .

But yes, there is no way to check right now unless you just try to use the APIs.

**Comment by cabanier** [comment] 2020-12-06 19:19
> @cabanier I don't think it's been in limbo for several years, it was specced a year ago .

No, it was proposed almost 4 years ago.

> Not sure what you mean on the spec front: the spec work here is complete, there is so far no implementation work in browsers though.

The implementation is complete in Chromium but behind a flag. During my Magic Leap days about 3 years ago, we had it enabled so we could detect enabled features.
If there is no movement we should add a flag to the layers spec so authors aren't forced to create dummy layers.

**Comment by Manishearth** [comment] 2020-12-06 21:35
> No, it was proposed almost 4 years ago

I mean sure, that's true of most of this spec, I thought you were talking about implementation

> The implementation is complete in Chromium but behind a flag.

I did a quick code search and it didn't seem to be?

**Comment by cabanier** [comment] 2020-12-07 11:19
> > The implementation is complete in Chromium but behind a flag.
> 
> I did a quick code search and it didn't seem to be?

See https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/modules/permissions/permissions.cc#L53

I just checked and it's already enabled in Chrome so we're good :-)

**Comment by klausw** [comment] 2020-12-07 19:27
@cabanier , this doesn't appear implemented yet in Chromium. The code you link to checks for named permissions, but this issue is about getting the status of required/optional features via permission queries which would need to be implemented separately.

if I'm reading it right, [Permissions::query](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/permissions/permissions.cc;l=53;drc=4ee318a3dd40f1f82f6dba8348f17154358e084d) calls [ParsePermissionDescriptor](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/permissions/permission_utils.cc;l=95;drc=38f8aed3833a0063dc63fdaba766d584cdb48264) which has case handling for various permissions, but I don't see any specific handling for the "xr" permission, and no code for `requiredFeatures`/`optionalFeatures` attributes from an XRPermissionDescriptor.

The only reference to XRPermissionDescriptor I can [find in Chromium source](https://source.chromium.org/search?q=requiredFeatures%20file:%5C.idl&ss=chromium) is in [third_party/blink/web_tests/external/wpt/interfaces/webxr.idl](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/web_tests/external/wpt/interfaces/webxr.idl;l=271;drc=dc7c12e156d3a374d7043ad6744e331b17c74f3e) which is part of web_tests, and separate from the IDL files used as part of the implementation such as [third_party/blink/renderer/modules/xr/xr_session_init.idl](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/xr/xr_session_init.idl) .

**Comment by klausw** [comment] 2020-12-07 19:37
To follow up, it seems that the implementation would need a new xr_permission_descriptor.idl file alongside the existing examples such as [camera_device_permission_descriptor.idl](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/permissions/camera_device_permission_descriptor.idl), conversion logic in [ParsePermissionDescriptor](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/permissions/permission_utils.cc;l=95;drc=38f8aed3833a0063dc63fdaba766d584cdb48264), and glue code to hook this up with the actual required/optionalFeatures logic in the XR code to answer queries about the current session.

@toji , I think you were more involved in the spec discussions around this, do you happen to know if there's an existing Chromium bug to implement this and/or concrete plans?

**Comment by Manishearth** [comment] 2020-12-07 21:59
Yeah, to be clear, Chrome implements `navigator.permissions.query()` just fine, but it doesn't know about `XRPermissionDescriptor` so you can't query any XR stuff.
