### ISSUE TITLE
Enumerate XR devices behavior

### ISSUE THREAD

**Issue by jungkees** [immersive-web/webxr#487] opened 2019-01-16 21:32 UTC
Some late feedback to https://github.com/immersive-web/webxr/issues/311.

I noticed the _enumerate XR devices_ in https://immersive-web.github.io/webxr/#xr-interface used MAY:
> The user agent MUST be able to enumerate XR devices attached to the system, at which time each available device is placed in the list of XR devices. Subsequent algorithms requesting enumeration MAY reuse the cached list of XR devices.

I'd like to understand what the rationale of using MAY here. I think we should avoid using MAY as much as we can to not cause compat issues. In this case, for example, different browsers can choose different devices when one is using a cache and the other is not.

In the same reason, I think we better use MUST instead of SHOULD below too:
> After the first enumeration the user agent SHOULD begin monitoring device connection and disconnection, adding connected devices to the list of XR devices and removing disconnected devices.

**Comment by kearwood** [comment] 2019-01-17 23:59
The use of "MAY" and "SHOULD" here has likely origins in WebVR and platform-level API's that did not enable the UA to conform to the spec requirements.  For example, detecting the tracking capabilities of a device could require the hardware to physically power on to detect the presence of the needed devices.

In the case of "MAY reuse the cached list of XR devices", the act of refreshing this cache is often an expensive operation which if called too many times could slow down the end-user's computer.  Perhaps if we were more explicit in the behavior, such functions could be fallible for the cause of throttling the requests and this could be surfaced to the WebXR API level.

As many hardware vendors are interacting with the immersive-web group, perhaps we can be more informed if such restrictions would still be required.

**Comment by toji** [comment] 2019-04-27 05:13
Fixed in https://github.com/immersive-web/webxr/commit/462780bb3b8c1055ec60261bd121dc979765af6a

**Closed by toji** 2019-04-27 05:13 UTC
Labels: spec bug
