### ISSUE TITLE
anchors as a core concept

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/webxr#337] opened 2018-03-28 11:40 UTC
While discussing the https://github.com/immersive-web/anchors proposal, the question of how fundamental we want anchors to be came up.

We've touched on this a number of times, but we should decide if we want to introduce anchors into VR as well as AR, to present an API that encourages a style of programming where all content is attached to anchors (i.e., make it so no content is just specified in a global coordinate system).

As we move from 3DOF and fixed-space VR gear, to inside-out devices that track their space, this will become necessary, so we should consider doing it now.

**Comment by judax** [comment] 2018-04-01 08:21
With the current proposal for anchors, VR could also use them although in most systems any created anchors won't ever be updated, most likely.

The main benefit is consistency between building VR and AR experiences. In AR experiences the use of anchors is highly recommended. If developers would understand anchors and start using them on any WebXR app they build, a more consistent ecosystem could be achieved. Also, as Blair indicates, a basic anchor could be used to specify the world origin, also justifying that anchors could have meaning in VR too, even in non-inside out systems.

**Comment by toji** [comment] 2018-04-03 21:49
Following up from the call today, it appears that some of the biggest hangups around using anchors everywhere is simply that the term "Anchor" has gained connotations that don't neatly fit into other uses that we have within WebXR. (Mapping the concept of an Anchor to the "headModel" frame of reference, for example, is awkward.) The proposed solution coming out of the call was to find a different, more neutral term to describe a single XR object type used to track spatial relationships and have the designation of "Anchor" vs "Frame of Reference", etc come from the way they are created. e.g. `requestFrameOfReference`, `requestAnchorAtPoint`, etc.)

At the moment we already have a base `XRCoordinateSystem` type that may serve that purpose well (it was intended to act as the base for both frames of reference and anchors). We could examine other possible names (`XRSpace`?) if needed. If we start using `XRCoordinateSystem` directly we would need to move some of the stage-specific stuff off of `XRFrameOfReference`, but that's likely a good idea anyway. (It would be nice to have the session describe stage bounds and be able to query them in relation to any coordinate system.)

**Comment by toji** [comment] 2018-04-03 23:00
Started a speculative pull request (#340) based on the above to facilitate more concrete conversation about that proposal.

**Comment by speigg** [comment] 2018-04-04 09:37
@toji I think not using anchors as the base class for generic spatial relationships is the right choice (doesn’t seem generic enough), although it seems that this is a different question than whether or not anchors (and/or trackables) should be a core concept in WebXR. The biggest challenge I see here is in arriving at a consensus about what anchors/trackables actually mean. 

That said, I opened an issue at https://github.com/immersive-web/anchors/issues/4 to compare what anchors/trackables actually mean on different platforms, and to have a discussion on what they might/should mean for WebXR.

**Comment by thetuvix** [comment] 2018-07-25 22:16
See #384 for a proposed tweak to `XRCoordinateSystem` that would enable it to support both static and dynamic objects.

With that change, `XRCoordinateSystem` itself (perhaps with a rename to something concise like `XRSpace`) can serve as the unifying currency underlying the poses of stages, freespace anchors, plane anchors, face anchors, mesh anchors, heads, hands, etc., whether those objects require time-indexing to align with photon time or not.

**Comment by NellWaliczek** [comment] 2018-09-12 22:42
Closing this issue in favor of the work being done in the anchors repo here: https://github.com/immersive-web/anchors

**Closed by NellWaliczek** 2018-09-12 22:42 UTC
