### ISSUE TITLE
Remove ProjectionMatrix in favor of FOV values?

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#461] opened 2019-01-04 01:46 UTC
This issue was raised in the discussion of #447.  The projection matrices were originally added instead of view-specific FOVs due to the behavior of certain hardware.  Now that this is no longer a requirement for those devices, it's been brought up that it might be better to return to representing the data as FOV values.  I'm not taking a stand one way or the other, but I didn't want this potential change to fall through the cracks.

Pros: 
* makes computing the combined culling frustum easier

Cons:
* potentially breaks hardware that doesn't currently exist which might require projection matrices with skew
* potential issues with diorama-style content

**Comment by NellWaliczek** [comment] 2019-01-04 01:49
An issue was also filed regarding providing a combined culling frustum in #203

**Comment by blairmacintyre** [comment] 2019-01-04 02:21
>     * potentially breaks hardware that doesn't currently exist which might require projection matrices with skew

That in not accurate.  Any display that needs an off-axis projection will not work with a simple FoV.  The most obvious example is any in-world display surface, such as a projector on a wall (i.e., or multiple projectors, like a CAVE) or a physical computer or laptop display, where the 3D graphics need to be rendered from the user's view-point (assuming the viewer is tracked relative to the display).

Similarly, a phone could use the user-facing camera to track the user, and then rendered from that viewpoint, a sort of "virtual transparency" effect could be created (here's a short paper talking about an implementation we did, published back in 2011). https://ieeexplore.ieee.org/document/6162897

**Comment by klausw** [comment] 2019-01-07 18:48
Such hardware already exist, for example the Pimax 5k+ headset which has started shipping to Kickstarter backers uses tilted screens. While it does have a "force parallel projection" mode to work with apps that can't handle skewed projection matrices, that has a performance cost and it would be preferable to support it natively.

SteamVR exposes projection matrices directly, AFAIK this was added recently specifically to help support such headsets. I think it would be a regression to do a lossy conversion to angles in WebXR.

Links for reference:

[SteamVR's IVRSystem::GetProjectionMatrix](https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetProjectionMatrix)

[Doc_Ok's article about issues with skewed screens, predates the SteamVR change](http://doc-ok.org/?p=1649)

[Kickstarter](https://www.kickstarter.com/projects/pimax8kvr/pimax-the-worlds-first-8k-vr-headset) 

[Review mentioning the "force parallel projections" settings, but confused about it](https://www.tomshardware.com/reviews/pimax-5k-m2-headset-vr,5818.html)

**Comment by klausw** [comment] 2019-01-07 19:18
I may have misunderstood this issue in my previous comment. Do we basically have several classes of projection matrices?

* Simple projection planes that are all parallel, or more specifically different views into the same plane, i.e. HMDs with coplanar displays. The view angles can be asymmetric. This is the most restrictive option, and some apps may incorrectly assume that projection planes are parallel.

* Tilted screens that can be expressed with top/bottom/left/right angles. I think this assumes that the top/bottom edges are horizontal and the left/right edges are vertical? This would support HMDs with tilted screens such as the Pimax 5k+, but may break apps that incorrectly assume parallel projection planes. To get the view angles for such a headset, you'd need to draw a perpendicular line from the eye to the projection plane, where the intersection point may be entirely outside the actual screen, and then measure angles from that to the screen edges.

* Rectangular screens in arbitrary positions such as the cases @blairmacintyre mentions in his comment, where the screen is rectangular but the edges aren't horizontal/vertical from the user's point of view. This requires a rotation in addition to left/right/top/bottom view angles?

* Fully general projection matrix including skew factors. I'm not sure if there's a use case for these?

Does that sound right? Would the "view angles" approach cover the typical "HMD with tilted screens" use case? Also, would it be feasible to support a non-horizontal/vertical screen via an added rotation angle without going all the way to a fully general projection matrix?

**Comment by klausw** [comment] 2019-01-07 19:37
Would be possible to support the "rectangular screen in arbitrary position" use case with a 4-angle projection description by including the roll rotation needed for aligning the screen edges into the view matrix? If I'm understanding it right, this would have the side effect that the app could no longer assume that "up" is in the -Y direction in view space, and multiple screens in arbitrary orientations would all have different "up" directions.

I think this wouldn't be an issue for a CAVE setup where the screens are all oriented vertically with the bottom edge parallel to the floor, but may cause app issues for use cases such as a cell phone held in an arbitrary position, or more complex configurations.

(Apologies for talking to myself on this issue, and this may well have been discussed already. However, I think it's a bit unclear from the issue description what the supported use cases and restrictions are for the proposal.)

**Comment by kearwood** [comment] 2019-01-07 23:47
Rather than switching from a matrix to FOV values, perhaps we could expose more information to help create the culling frustum?  Or perhaps, a function that can return a culling frustum directly?

Some devices also include a stencil mask for excluding rendering from non-visible regions of the display.  I could imagine that the browser could do a better job of ubiquitously taking things like this into account.

I would suggest that such an api give the option to retrieve either a simplified cuboid or an arbitrary (but guaranteed convex) mesh.

**Comment by kearwood** [comment] 2019-01-07 23:52
For reference:

https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetHiddenAreaMesh

When available, a browser would extrude this volume and find the extents that best fit the requested simplied / arbitrary culling volume mesh.

**Comment by kearwood** [comment] 2019-01-07 23:53
Even if we expose something like IVRSystem::GetHiddenAreaMesh in WebXR, perhaps there is value in a function that ubiquitously works and takes into consideration new functionality added in the future that the page is not aware of when written.

**Comment by kearwood** [comment] 2019-01-08 00:00
FWIW, I've added an issue suggesting exposing the hidden area mesh also:

https://github.com/immersive-web/webxr/issues/463

**Comment by cwilso** [comment] 2019-01-09 18:38
Goal for FTF is to decide which of these paths to take.

**Comment by thetuvix** [comment] 2019-01-14 19:34
I agree with @kearwood that if we care about runtimes influencing the combined culling frustum calculation, we should just provide such a frustum directly from the API.

For me, the primary goal of moving to an `angleUp`/`angleDown`/`angleLeft`/`angleRight` FOV representation for projections is to simplify WebXR's contract with apps, whose shaders may not be written to handle fully-generic projection matrices that include roll/shear/etc.  If an app decomposes the provided projection matrix before feeding it into their rendering, and their math drops the roll or shear components, the design of WebXR does not allow the app to submit the projection matrix it actually used.  This prevents the underlying XR runtime from correcting for the app's behavior during reprojection, which it would otherwise be able to do with today's native XR APIs.

As a case study, HoloLens previously had a subtle shear component in its projection matrix, but we now handle this bit of calibration elsewhere in the stack.  Even in engines that supported projection matrices with shear, we've found this change to better fit assumptions made in the app's own shaders.  App developers are often more likely to chalk up subtle visual quality issues to device limitations rather than misassumptions on their side - having the platform better fit those app assumptions can increase quality for everyone.

@klausw laid out the more generic version of this problem, with a ladder of different assumptions that apps may make.  To his point, we've also seen desktop VR apps whose full-screen shader effects further assume parallel view transforms that then got confused when presented with non-parallel transforms for slightly-tilted panels.  There, we've gone the other way and continued to provide non-parallel view transforms, working with app vendors to fix up their apps.  However, for the web, I could see a more granular solution here that let apps opt in to the level of view/projection complexity that their rendering logic and shaders have been tested against.  Engines that allow apps to write their own custom shaders would be strongly encouraged to then expose this choice through to their own app developers.

@blairmacintyre: Regarding the necessity of roll/shear for diorama-style devices/scenarios, the same topic came up in another context and Doug Twilleager from zSpace mentioned their own similar history here - a long time ago, they'd report a projection matrix that included the roll/shear, but now they just incorporate that into the per-eye view transform.  Do you have cases in mind where that representation would be insufficient?

@rcabanier: Last week, I heard someone from Magic Leap mention in another context that their projection matrices _**do**_ currently include a shear component.  Do you know if this shear component is similarly amenable to instead being incorporated into the per-eye view transforms for WebXR, similar to what zSpace does?  I expect that this would improve app compatibility for AR web content across devices.

**Comment by rcabanier** [comment] 2019-01-14 21:56
@thetuvix We get custom view and projection matrices for each frame and each eye from the graphics subsystem and I verified that there is a shear applied to the projection:
 ```
 [[2.842104, 0.000000, 0.000000, 0.000000]
  [0.000000, 3.897521, 0.000000, 0.000000]
  [-0.000893, -0.004491, -1.171066, -1.000000]
  [0.000000, 0.000000, -0.839120, 0.000000]]
```
Can you elaborate on this?
> Do you know if this shear component is similarly amenable to instead being incorporated into the per-eye view transforms for WebXR, similar to what zSpace does?

[This document](https://drive.google.com/file/d/1h36TJRkK4KteRUVcoXAnbHzTFfuz6m-q/view) has a bit more information on how we get to the matrices

**Comment by thetuvix** [comment] 2019-01-14 23:01
@rcabanier My understanding is that zSpace was originally in a similar situation as Magic Leap, providing apps a projection matrix for each eye that included a shear component (and in their case, a roll component).  However, since then, zSpace has moved to an approach where they represent the eye's off-axis position/orientation relative to the screen by instead adjusting the position and orientation of that eye's view transform.  This allowed them to provide apps a more standard projection matrix that can be represented completely with `angleUp`/`angleDown`/`angleLeft`/`angleRight` (plus ultimately an app-decided near/far plane).  Each eye's view transform would then be adjusted each frame as needed to represent the motion of the eye relative to the display.

I could see Magic Leap's WebXR implementation pursuing a similar approach.  If it's possible for a Magic Leap UA to produce a similar `angleUp`/`angleDown`/`angleLeft`/`angleRight` projection specification and modified view transform each frame that achieves equivalent results to your current view/projection matrices (and then accept frames rendered with those matrices), we could establish a stronger contract with WebXR developers, promising that they won't need to consider shear or roll components in their shaders.  There may well be some reason that this is not possible given Magic Leap's optics or that it's possible but produces suboptimal visual quality, but it's worth seeing if the math works out here, as this alignment could help WebXR achieve greater compatibility for content across all XR devices.

**Comment by klausw** [comment] 2019-01-14 23:03
The way I understand it, the combination of an arbitrary rigid view transform and four FOV angles should work for a rectangular screen at any position or orientation. (Excluding pathological cases such as seeing the screen exactly edge on which would put the eye inside the projection plane.)

The rectangular view screen defines a projection plane. As the projection center, use the closest point to the eye, where the eye-to-projection-center line is perpendicular to the plane, along the plane's normal vector. (This may be outside the screen, that's OK as long is it's on the plane containing the screen.) This eye-to-projection-point line specifies the view's "forward" vector. Next, do a roll rotation around the eye-to-projection-point line so that the view "right" vector is parallel to the top and bottom edges of the screen. Now, measure the angles from the projection point to the left/right/top/bottom screen edges to define the projection matrix. Does that sound right?

I'm not sure how skew factors work, but I think this would be needed to express non-rectangular screens, such as a projector that's not perpendicular to the screen. In this case, I assume the projection matrix would basically be doing keystone correction? I don't think it would be possible to move this part into a rigid transform (translation and rotation only) view matrix. If you wanted to make this work, I think you'd need to have the app draw to a rectangular screen that's perpendicular to the projector, and then apply a separate post-rendering transform to do keystone correction on it for output. I think this is similar to what Pimax does when the "force parallel projection" option is set, though in that case it's used to ensure that both rendering screens share a parallel projection plane.

Of course, if the view matrix were an arbitrary matrix, any part of the projection matrix could be moved into it, but I assume that's not what we're talking about here.

**Comment by rcabanier** [comment] 2019-01-14 23:58
@thetuvix I talked to the head of our graphics team and he said that moving the shear component to the view matrix is not going to work because our extrinsics have a rotation. (see the doc I attached earlier)
According to him, it's much better for the platform to create the projection matrix instead of relying on the user to do it correctly.

If you want, I can work with him on a more extensive reply or invite him to next week's call.

**Comment by thetuvix** [comment] 2019-01-15 21:57
@rcabanier We should perhaps separate out two independent things to nail down here in the WebXR spec:
* Does the WebXR API physically deliver the platform projections to apps as a matrix or as 4 FOV angles?
* Does the WebXR spec promise that projections provided to apps must be decomposable exactly to 4 FOV angles?

Even if we decide to deliver projections as matrices to avoid relying on devs to that recomposition right, we still need to document what assumptions those devs can make or not make about the matrices they get back.

**Comment by klausw** [comment] 2019-01-16 01:12
I agree about the need to document assumptions for developers. In addition to the ones @thetuvix mentions above, we have some more basic assumptions:

* does the spec allow views to have non-parallel view directions with non-coplanar projection planes?
* can the combined FoV of the individual views equal or exceed 180 degrees?

I think both of these are true in the current spec independent of the discussion in this issue, but I suspect that developers may not be aware of this flexibility and make incorrect assumptions.

**Comment by klausw** [comment] 2019-01-16 19:15
@rcabanier - the projection matrix from your example above appears to be a standard projection matrix, I don't see any unusual values in it.

Using the definitions from http://www.songho.ca/opengl/gl_projectionmatrix.html, and taking into account that your example is transposed from the version shown there, I end up with the following equalities:

```
2 * n / (r - l) = 2.842104
2 * n / (t - b) = 3.897521
(r + l) / (r - l) = -0.000893
(t + b) / (t - b) = -0.004491
- (f + n) / (f - n) = -1.171066
- 2 * f * n / (f - n) = -0.839120
```

Solving these in Emacs Calc, I get:
```
[f = 4.90524125191, n = 0.386501377664]
[r = 0.135869845697, l = -0.136112726133, t = 0.0987205970097, b = -0.0996113055843]
```

As sanity check, here's the result of substituting those values into the projection matrix equation:

```
    [ [   2 n / (r - l),           0,                 0,          0  ]
      [         0,           2 n / (t - b),           0,          0  ]
      [ (r + l) / (r - l), (t + b) / (t - b), -(f + n) / (f - n), -1 ]
      [         0,                 0,          -2 f n / (f - n),  0  ] ]
=>
    [ [ 2.842104,      0,         0,     0  ]
      [     0,     3.897521,      0,     0  ]
      [ -0.000893, -0.004491, -1.171066, -1 ]
      [     0,         0,     -0.839120, 0  ] ]
```

That looks exactly equal to the input matrix:

```
[[2.842104, 0.000000, 0.000000, 0.000000]
 [0.000000, 3.897521, 0.000000, 0.000000]
 [-0.000893, -0.004491, -1.171066, -1.000000]
 [0.000000, 0.000000, -0.839120, 0.000000]]
```

So unless I messed up the calculations, it looks as if Magic Leap doesn't need anything unusual and would also work with projections specified via top/right/bottom/left angles + near/far distances.

**Comment by rcabanier** [comment] 2019-01-18 22:55
I asked our graphics team to write a detailed explanation why FOV angles + distances won't suffice for us. Maybe I can get someone to call in to discuss it.

**Comment by klausw** [comment] 2019-01-18 23:18
@rcabanier thank you! The part that confuses me is that the sample matrix from your [previous comment](https://github.com/immersive-web/webxr/issues/461#issuecomment-454176884) appears to be a plain projection matrix that can be expressed losslessly with just FOV angles + distances. When you're saying that those parameters won't suffice, is that related to a different version of the APIs that returns a different type of projections? If yes, do you have an example of such a matrix?

I think there may be a disconnect here about how the views are being set up. Apart from the projection matrix, each view has its own independent RigidTransform, so per-eye variations such as differing forward directions or tilted screens would be represented there, not in the projection matrix.

**Closed** 2019-04-01 18:09 UTC
Labels: potential breaking change
